### ISSUE TITLE
Improvement tracker

### ISSUE THREAD

**Issue by EricRabil** [EricRabil/Swog#3]
- [ ] Use native OSLogInterpolation on supported OS releases
- [ ] Allow suppression of subsystems/categories/logging levels
- [ ] OSS the Promtail driver
- [ ] OSS the SWError class (has backtracing, nesting, contexts, serialization, Swog support, etc.)
